# Generated by Django 3.1.2 on 2021-01-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201129_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='websiteuser',
            name='user_birthday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
